#ifndef ADC24_CHANNEL_DEF_H_
#define ADC24_CHANNEL_DEF_H_

#include "cmds.h"

#define ADC24_DATA_N_BYTES 3

typedef enum
{
	ADC24_LOWER_THRESHOLD,
	ADC24_UPPER_THRESHOLD,
	ADC24_REFRESH_DIVIDER
} ADC24_VARIABLES;

typedef enum
{
	ADC24_REQ_RESET_SETTINGS = COMMON_REQ_RESET_SETTINGS,	// NO payload
	ADC24_RES_RESET_SETTINGS = COMMON_RES_RESET_SETTINGS,	// NO payload
	ADC24_REQ_STATUS = COMMON_REQ_STATUS,					// NO payload
	ADC24_RES_STATUS = COMMON_RES_STATUS,					// TODO: some status msg
	ADC24_REQ_SET_VARIABLE = COMMON_REQ_SET_VARIABLE,		// SetMsg_t
	ADC24_RES_SET_VARIABLE = COMMON_RES_SET_VARIABLE,		// SetMsg_t
	ADC24_REQ_GET_VARIABLE = COMMON_REQ_GET_VARIABLE,		// GetMsg_t
	ADC24_RES_GET_VARIABLE = COMMON_RES_GET_VARIABLE,		// SetMsg_t
	ADC24_REQ_CALIBRATE = COMMON_TOTAL_CMDS,				// NO payload
	ADC24_RES_CALIBRATE,           							 // NO payload

	ADC24_TOTAL_CMDS
} ADC24_CMDs;

#endif
