#ifndef CONTROL_CHANNEL_DEF_H_
#define CONTROL_CHANNEL_DEF_H_

#include "cmds.h"

#define CONTROL_DATA_N_BYTES 2

typedef enum
{
	CONTROL_ENABLED,
	CONTROL_TARGET,
	CONTROL_THRESHOLD,
	CONTROL_HYSTERESIS,
	CONTROL_REFRESH_DIVIDER
} CONTROL_VARIABLES;

typedef enum
{
	CONTROL_REQ_RESET_SETTINGS = COMMON_REQ_RESET_SETTINGS,	// NO payload
	CONTROL_RES_RESET_SETTINGS = COMMON_RES_RESET_SETTINGS,	// NO payload
	CONTROL_REQ_STATUS = COMMON_REQ_STATUS,					// NO payload
	CONTROL_RES_STATUS = COMMON_RES_STATUS,					// TODO: some status msg
	CONTROL_REQ_SET_VARIABLE = COMMON_REQ_SET_VARIABLE,		// SetMsg_t
	CONTROL_RES_SET_VARIABLE = COMMON_RES_SET_VARIABLE,		// SetMsg_t
	CONTROL_REQ_GET_VARIABLE = COMMON_REQ_GET_VARIABLE,		// GetMsg_t
	CONTROL_RES_GET_VARIABLE = COMMON_RES_GET_VARIABLE,		// SetMsg_t
	// = COMMON_TOTAL_CMDS,						// NO payload

	CONTROL_TOTAL_CMDS
} CONTROL_CMDs;

#endif
