#ifndef DIGITAL_OUT_CHANNEL_DEF_H_
#define DIGITAL_OUT_CHANNEL_DEF_H_

#include "cmds.h"

#define DIGITAL_OUT_DATA_N_BYTES 2

typedef enum
{
	DIGITAL_OUT_STATE,
	DIGITAL_OUT_DUTY_CYCLE,
	DIGITAL_OUT_FREQUENCY,
	DIGITAL_OUT_MEASUREMENT,
	DIGITAL_OUT_SENSOR_REFRESH_DIVIDER,
} DIGITAL_OUT_VARIABLES;

typedef enum
{
	DIGITAL_OUT_REQ_RESET_SETTINGS = COMMON_REQ_RESET_SETTINGS,	// NO payload
	DIGITAL_OUT_RES_RESET_SETTINGS = COMMON_RES_RESET_SETTINGS,	// NO payload
	DIGITAL_OUT_REQ_STATUS = COMMON_REQ_STATUS,					// NO payload
	DIGITAL_OUT_RES_STATUS = COMMON_RES_STATUS,					// TODO: some status msg
	DIGITAL_OUT_REQ_SET_VARIABLE = COMMON_REQ_SET_VARIABLE,		// SetMsg_t
	DIGITAL_OUT_RES_SET_VARIABLE = COMMON_RES_SET_VARIABLE,		// SetMsg_t
	DIGITAL_OUT_REQ_GET_VARIABLE = COMMON_REQ_GET_VARIABLE,		// GetMsg_t
	DIGITAL_OUT_RES_GET_VARIABLE = COMMON_RES_GET_VARIABLE,		// SetMsg_t
	// = COMMON_TOTAL_CMDS,
	DIGITAL_OUT_TOTAL_CMDS
} DIGITAL_OUT_CMDs;


#endif
